### ISSUE TITLE
大神，请问您训练的这个模型重现论文结果了吗？

### ISSUE THREAD

**Issue by zxt881108** [panda-lab/faceboxes#1]
在fddb和wider face上结果是多少？另外solver怎么配的？谢谢！

**Comment by zxt881108** [comment]
另外，请问这个模型在训练的时候是直接初始化的还是从其他数据集先pretrain的？

**Comment by panda-lab** [comment]
@zxt881108  fddb上90左右，有人做到了93。

**Comment by Cv9527** [comment]
@lsy17096535 能否分享训练code?

**Comment by KeyKy** [comment]
请问这个模型在训练的时候是直接初始化的还是从其他数据集先pretrain的？

**Comment by jnulzl** [comment]
@lsy17096535 敢问哪位大神在FDDB上做到了93%？

**Comment by mai00dou** [comment]
![discroc_1024_no_density_98000](https://user-images.githubusercontent.com/9097858/44829566-05d4e680-ac50-11e8-9b90-3af86f0ddf76.png)

**Comment by mai00dou** [comment]
这个目前只训练了98000轮

**Comment by panda-lab** [comment]
@mai00dou  这么高？很厉害，能贡献下model吗？

**Comment by mai00dou** [comment]
@lsy17096535 我还在优化，本周内会给你提供一个model

**Comment by mai00dou** [comment]
@lsy17096535 给我你的邮箱，我给你一个版本，

**Comment by panda-lab** [comment]
@mai00dou lsy17096535@126.com. 非常感谢。

**Comment by Salary-only-17k** [comment]
redstormth@live.com 谢谢大婶分享一个吧 @mai00dou

**Comment by Salary-only-17k** [comment]
redstormth@live.com 谢谢大神分享一个吧 @lsy17096535

**Comment by panda-lab** [comment]
@WhiteAzzan  整理完共享出来。

**Comment by Salary-only-17k** [comment]
@lsy17096535  谢谢大大

**Comment by yja1** [comment]
@lsy17096535 一直没有跑到论文里得效果。求一个效果好的model非常感谢

**Comment by panda-lab** [comment]
@yja1 我们也没有完全复现论文的效果，目前没有再深入这一块的研究。

**Comment by ramanathan831** [comment]
@mai00dou  @lsy17096535 @WhiteAzzan , Can any one please share the model which achieved >0.95. 
**Email: ram0181997@gmail.com**
