### ISSUE TITLE
编译通过，但是forward时异常报错

### ISSUE THREAD

**Issue by lyk125** [panda-lab/faceboxes#4]
您好：
       我在ssd的caffe分支中，替换掉原ssd的prior_box_layer.cpp文件，编译没有问题，但是在执行"caffe time"测试耗时时，出异常了：
I1016 15:07:06.467943  7093 net.cpp:283] Network initialization done.
I1016 15:07:06.468346  7093 caffe.cpp:355] Performing Forward
*** Aborted at 1508137626 (unix time) try "date -d @1508137626" if you are using GNU date ***
PC: @     0x7f091b5cd78d caffe::PriorBoxLayer<>::Forward_cpu()
*** SIGSEGV (@0x0) received by PID 7093 (TID 0x7f091bb86a40) from PID 0; stack trace: ***
    @     0x7f0919952cb0 (unknown)
    @     0x7f091b5cd78d caffe::PriorBoxLayer<>::Forward_cpu()
    @     0x7f091b6f02da caffe::Net<>::ForwardFromTo()
    @     0x7f091b6f04b7 caffe::Net<>::Forward()
    @           0x4090ea time()
    @           0x4062ac main
    @     0x7f091993df45 (unknown)
    @           0x406bb3 (unknown)
    @                0x0 (unknown)
*** Error in `./build/tools/caffe': malloc(): memory corruption: 0x0000000002052d00 ***
Aborted (core dumped)
应该是prior_box_layer.cpp引入的；
是我使用的caffe分支有问题，还是别的问题呢？望解答，谢谢！

**Comment by panda-lab** [comment]
@lyk125  不需要测试，直接可以用，过几天提供全部训练代码，不需要修改caffe 源码.
